export const projects = [
  {
    title: 'Website Movies',
    description: "",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'JAVASCRIPT', 'RESPONSIVE'],
    source: 'https://va-st.github.io/website-movies/',
    visit: 'https://github.com/VA-ST/website-movies',
    id: 0,
  },
  {
    title: 'Clon Animal Crossing',
    description:"",
    image: '/images/2.png',
    tags: ['HTML','CSS', 'JAVASCRIPT', 'BOOTSTRAP'],
    source: 'https://va-st.github.io/clon_animal_crossing/',
    visit: 'https://github.com/VA-ST/clon_animal_crossing',
    id: 1,
  },
  {
    title: 'Color Bomba',
    description: "",
      image: '/images/3.png',
      tags: ['HTML','CSS','JAVASCRIPT'],
    source: 'https://va-st.github.io/color-bomba/',
    visit: 'https://github.com/VA-ST/color-bomba',
    id: 2,
  },
  {
    title: 'Calculadora Simple',
    description: "",
    image: '/images/4.png',
    tags: ['HTML','CSS','JAVASCRIPT'],
    source: 'https://va-st.github.io/Calculator-Simple/',
    visit: 'https://github.com/VA-ST/Calculator-Simple',
    id: 3,
  },
  {
    title: 'Website Planets',
    description: "",
    image: '/images/5.png',
    tags: ['HTML','CSS','JAVASCRIPT','PARALLAX','GSAP'],
    source: 'https://va-st.github.io/parallax-planets/',
    visit: 'https://github.com/VA-ST/parallax-planets',
    id: 4,
  },
  {
    title: 'Diseño Login',
    description: "",
    image: '/images/6.png',
    tags: ['HTML','CSS','JAVASCRIPT'],
    source: 'https://va-st.github.io/responsive-sliding-login-form/',
    visit: 'https://github.com/VA-ST/responsive-sliding-login-form',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Graduado como Tecnico Superior en Informatica', },
  { year: 2018, text: 'Graduado como Ingeniero Electronico', },
  { year: 2019, text: 'Trabaje como ingeniero programando en lenguaje C++', },
  { year: 2020, text: 'Comence a Dedicarme al desarrollo Web', },
  { year: 2022, text: 'Comence el desarrollo de un blog para que las personas puedan aprender', },
];